export enum AssetType {
  EQUITY = "EQUITY",
  MUTUAL_FUND = "MUTUAL_FUND",
  OPTION = "OPTION",
  FUTURE = "FUTURE",
  FOREX = "FOREX",
  INDEX = "INDEX",
  CASH_EQUIVALENT = "CASH_EQUIVALENT",
  FIXED_INCOME = "FIXED_INCOME",
  PRODUCT = "PRODUCT",
  CURRENCY = "CURRENCY",
  COLLECTIVE_INVESTMENT = "COLLECTIVE_INVESTMENT",
}

export enum CashEquivalentTypeEnum {
  SWEEP_VEHICLE = "SWEEP_VEHICLE",
  SAVINGS = "SAVINGS",
  MONEY_MARKET_FUND = "MONEY_MARKET_FUND",
  UNKNOWN = "UNKNOWN",
}

export enum CollectiveInvestmentTypeEnum {
  UNIT_INVESTMENT_TRUST = "UNIT_INVESTMENT_TRUST",
  EXCHANGE_TRADED_FUND = "EXCHANGE_TRADED_FUND",
  CLOSED_END_FUND = "CLOSED_END_FUND",
  INDEX = "INDEX",
  UNITS = "UNITS",
}

export enum TransactionEquityTypeEnum {
  COMMON_STOCK = "COMMON_STOCK",
  PREFERRED_STOCK = "PREFERRED_STOCK",
  DEPOSITORY_RECEIPT = "DEPOSITORY_RECEIPT",
  PREFERRED_DEPOSITORY_RECEIPT = "PREFERRED_DEPOSITORY_RECEIPT",
  RESTRICTED_STOCK = "RESTRICTED_STOCK",
  COMPONENT_UNIT = "COMPONENT_UNIT",
  RIGHT = "RIGHT",
  WARRANT = "WARRANT",
  CONVERTIBLE_PREFERRED_STOCK = "CONVERTIBLE_PREFERRED_STOCK",
  CONVERTIBLE_STOCK = "CONVERTIBLE_STOCK",
  LIMITED_PARTNERSHIP = "LIMITED_PARTNERSHIP",
  WHEN_ISSUED = "WHEN_ISSUED",
  UNKNOWN = "UNKNOWN",
}

export enum FixedIncomeTypeEnum {
  BOND_UNIT = "BOND_UNIT",
  CERTIFICATE_OF_DEPOSIT = "CERTIFICATE_OF_DEPOSIT",
  CONVERTIBLE_BOND = "CONVERTIBLE_BOND",
  COLLATERALIZED_MORTGAGE_OBLIGATION = "COLLATERALIZED_MORTGAGE_OBLIGATION",
  CORPORATE_BOND = "CORPORATE_BOND",
  GOVERNMENT_MORTGAGE = "GOVERNMENT_MORTGAGE",
  GNMA_BONDS = "GNMA_BONDS",
  MUNICIPAL_ASSESSMENT_DISTRICT = "MUNICIPAL_ASSESSMENT_DISTRICT",
  MUNICIPAL_BOND = "MUNICIPAL_BOND",
  OTHER_GOVERNMENT = "OTHER_GOVERNMENT",
  SHORT_TERM_PAPER = "SHORT_TERM_PAPER",
  US_TREASURY_BOND = "US_TREASURY_BOND",
  US_TREASURY_BILL = "US_TREASURY_BILL",
  US_TREASURY_NOTE = "US_TREASURY_NOTE",
  US_TREASURY_ZERO_COUPON = "US_TREASURY_ZERO_COUPON",
  AGENCY_BOND = "AGENCY_BOND",
  WHEN_AS_AND_IF_ISSUED_BOND = "WHEN_AS_AND_IF_ISSUED_BOND",
  ASSET_BACKED_SECURITY = "ASSET_BACKED_SECURITY",
  UNKNOWN = "UNKNOWN",
}

export enum ForexTypeEnum {
  STANDARD = "STANDARD",
  NBBO = "NBBO",
  UNKNOWN = "UNKNOWN",
}

export enum FutureTypeEnum {
  STANDARD = "STANDARD",
  UNKNOWN = "UNKNOWN",
}

export enum IndexTypeEnum {
  BROAD_BASED = "BROAD_BASED",
  NARROW_BASED = "NARROW_BASED",
  UNKNOWN = "UNKNOWN",
}


export enum MutualFundTypeEnum {
  NOT_APPLICABLE = "NOT_APPLICABLE",
  OPEN_END_NON_TAXABLE = "OPEN_END_NON_TAXABLE",
  OPEN_END_TAXABLE = "OPEN_END_TAXABLE",
  NO_LOAD_NON_TAXABLE = "NO_LOAD_NON_TAXABLE",
  NO_LOAD_TAXABLE = "NO_LOAD_TAXABLE",
  UNKNOWN = "UNKNOWN",
}

export enum PutCallEnum {
  PUT = 'PUT',
  CALL = 'CALL',
  UNKNOWN = 'UNKNOWN',
}

export enum OptionTypeEnum {
  VANILLA = "VANILLA",
  BINARY = "BINARY",
  BARRIER = "BARRIER",
  UNKNOWN = "UNKNOWN",
}

export enum ProductTypeEnum {
  TBD = "TBD",
  UNKNOWN = "UNKNOWN",
}
