
export enum AssetType {
  EQUITY = "EQUITY",
  MUTUAL_FUND = "MUTUAL_FUND",
  OPTION = "OPTION",
  FUTURE = "FUTURE",
  FOREX = "FOREX",
  INDEX = "INDEX",
  CASH_EQUIVALENT = "CASH_EQUIVALENT",
  FIXED_INCOME = "FIXED_INCOME",
  PRODUCT = "PRODUCT",
  CURRENCY = "CURRENCY",
  COLLECTIVE_INVESTMENT = "COLLECTIVE_INVESTMENT",
}
